export const mockSubscriptions = [
    {
        id: 1,
        name: "Netflix Premium",
        category: "エンタメ",
        amount: "¥1,980",
        cycle: "月額",
        nextBilling: "2025-12-15",
        status: "利用中",
        logo: "N",
        color: "bg-red-600",
        startDate: "2023-01-01",
        endDate: null,
        image: "https://logo.clearbit.com/netflix.com",
    },
    {
        id: 2,
        name: "Spotify Duo",
        category: "音楽",
        amount: "¥1,280",
        cycle: "月額",
        nextBilling: "2025-12-20",
        status: "利用中",
        logo: "S",
        color: "bg-green-500",
        startDate: "2023-08-01",
        endDate: null,
        image: "https://logo.clearbit.com/spotify.com",
    },
    {
        id: 3,
        name: "Adobe Creative Cloud",
        category: "仕事効率化",
        amount: "¥7,780",
        cycle: "月額",
        nextBilling: "2025-12-25",
        status: "利用中",
        logo: "A",
        color: "bg-blue-600",
        startDate: "2023-10-01",
        endDate: null,
    },
    {
        id: 4,
        name: "Amazon Prime",
        category: "ショッピング",
        amount: "¥5,900",
        cycle: "年額",
        nextBilling: "2024-08-12",
        status: "利用中",
        logo: "A",
        color: "bg-blue-400",
        startDate: "2022-08-12",
        endDate: null,
        image: "https://logo.clearbit.com/amazon.co.jp",
    },
    {
        id: 5,
        name: "DAZN",
        category: "スポーツ",
        amount: "¥3,700",
        cycle: "月額",
        nextBilling: "-",
        status: "解約済",
        logo: "D",
        color: "bg-gray-800",
        startDate: "2023-04-01",
        endDate: "2023-09-30",
        image: "https://logo.clearbit.com/dazn.com",
    },
    {
        id: 6,
        name: "Apple Music",
        category: "音楽",
        amount: "¥1,080",
        cycle: "月額",
        nextBilling: "2025-12-10",
        status: "利用中",
        logo: "A",
        color: "bg-red-500",
        startDate: "2023-11-01",
        endDate: null,
        image: "https://logo.clearbit.com/apple.com",
    },
    {
        id: 7,
        name: "Hulu Premium",
        category: "エンタメ",
        amount: "¥1,500",
        cycle: "月額",
        nextBilling: "2025-12-31",
        status: "利用中",
        logo: "H",
        color: "bg-purple-600",
        startDate: "2023-05-01",
        endDate: null,
        image: "https://logo.clearbit.com/hulu.com",
    },
    {
        id: 8,
        name: "YouTube Premium",
        category: "エンタメ",
        amount: "¥1,180",
        cycle: "月額",
        nextBilling: "2025-12-31",
        status: "利用中",
        logo: "Y",
        color: "bg-red-500",
        startDate: "2023-06-01",
        endDate: null,
        image: "https://logo.clearbit.com/youtube.com",
    },
    {
        id: 9,
        name: "Disney+",
        category: "エンタメ",
        amount: "¥990",
        cycle: "月額",
        nextBilling: "2025-12-31",
        status: "利用中",
        logo: "D",
        color: "bg-blue-600",
        startDate: "2023-07-01",
        endDate: null,
        image: "https://logo.clearbit.com/disneyplus.com",
    },
];

export const userPlan = {
    type: 'premium', // 'free' | 'premium'
    limit: Infinity, // 無制限
    price: 200
};
